language: node_js
node_js: "lts/*"
script: 
  - npm install
  - npm run build
  - npm run heroku-deploy

#deploy:
#  provider: heroku
#  api_key:
#    secure: YaBjKOqKkoWbfH0Gfd4679YoVPHrisvQ4urVJ/JrGxfk74PiIxcVIjfB0AoehnaoVcBZolNBQ9pGE879aed6n7iOrKjpxf/3pn8wkF0QdZsz785bLqwKrxDSpu83KThuhmR7RMeINdsEw1Ayn1abgYcY0fj4P3mRECjwfI+0v/hh66n6tFCfiiQKOoh26lUsh0KrOUykGHs/2vnb2DFAE1A6FHN+ArDnUKbVLtAOp9xM2+ZX3px2Oeajw/Wj6Jvw2REYv1gOxwfu/BbqrvSApLjSdeTKgXbHPAPk3TqWgKC+z+yCD3XBi3nY23sr1cGhuqfqoJm1wnZxGr1nJ4DeExs1bxmFL2DYVx4TRVs13qcKtvylYNRSY40S8jRj4+QtV8SCX5nKjKEN43BYDj/Vas40gBTe5PuAxDMXePWif1RcRUlMMqrw7IU7UnPHs6tPcrGj+QC23ilMvShlLy6IFZ4nWENthkMIQ7BTC8mCwwg4pP6ucR2p3h1+SwbUHDE/Dad9+epO+A2ckriWBsNodR/e+3kABFXBGRD2VWzSXBNjEmSQT0oiXrv3/CLYL3ucNt0tQL3VLvg25N7KrKXkN988Eo24OarfHZR3Mzd1c4TVERsDc+WaWxlpQM22Zfzvus+W6WOtcc4ZqacJl4TTnvajxEM6HHmqwk+jkeB82OI=
#  run: npm run deploy
